[buildPlans.Sevka]
family = "sevka"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Sevka.variants]
  inherits = "ss15"

    [buildPlans.Sevka.variants.design]
    one = "base"
    two = "curly-neck-serifless"
    four = "open"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    nine = "open-contour"
    zero = "slashed-cutout"
    capital-q = "crossing-baseline"
    z = "straight-serifless-with-crossbar"
    lower-lambda = "straight-turn"
    lower-upsilon = "casual-serifless"
    lower-psi = "serifed"
    tittle = "square"
    diacritic-dot = "square"
    punctuation-dot = "square"
    braille-dot = "square"
    asterisk = "penta-low"
    underscore = "low"
    caret = "high"
    paren = "large-contour"
    number-sign = "upright-tall"
    at = "fourfold-solid-inner-tall"
    dollar = "open"
    cent = "open"
    percent = "dots"
    micro-sign = "tailed-serifless"

    [buildPlans.Sevka.variants.italic]
    a = "single-storey-earless-corner-tailed"
    e = "rounded"
    f = "tailed"
    i = "tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    m = "tailed-serifless"
    n = "tailed-serifless"
    q = "diagonal-tailed-serifless"
    r = "earless-rounded-serifless"
    t = "diagonal-tailed"
    u = "tailed-serifless"
    x = "cursive"
    z = "cursive-with-crossbar"
    lower-delta = "rounded"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"

[buildPlans.Sevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Sevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Sevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Sevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Sevka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Sevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Sevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
